
const $=id=>document.getElementById(id);
const canvas=$("canvas"),ctx=canvas.getContext("2d");
let reel=null;let generationSeq=0;let previewRAF=null;let renderRunning=false;let voiceBuffer=null;let voiceBlobUrl=null;let activeAudioContext=null;let activeNodes=[];let generationController=null;
const languages={
 en:{name:"English",locale:"en-IN"},hi:{name:"Hindi",locale:"hi-IN"},bn:{name:"Bengali",locale:"bn-IN"},or:{name:"Odia",locale:"or-IN"},ta:{name:"Tamil",locale:"ta-IN"},te:{name:"Telugu",locale:"te-IN"},mr:{name:"Marathi",locale:"mr-IN"},gu:{name:"Gujarati",locale:"gu-IN"},kn:{name:"Kannada",locale:"kn-IN"},ml:{name:"Malayalam",locale:"ml-IN"},pa:{name:"Punjabi",locale:"pa-IN"},ur:{name:"Urdu",locale:"ur-IN"},fr:{name:"French",locale:"fr-FR"},es:{name:"Spanish",locale:"es-ES"},de:{name:"German",locale:"de-DE"},it:{name:"Italian",locale:"it-IT"},pt:{name:"Portuguese",locale:"pt-BR"},ru:{name:"Russian",locale:"ru-RU"},ja:{name:"Japanese",locale:"ja-JP"},ko:{name:"Korean",locale:"ko-KR"},"zh-CN":{name:"Chinese",locale:"zh-CN"},ar:{name:"Arabic",locale:"ar-SA"},tr:{name:"Turkish",locale:"tr-TR"},nl:{name:"Dutch",locale:"nl-NL"},pl:{name:"Polish",locale:"pl-PL"}
};
function setProgress(n,text){$("progressBar").style.width=Math.max(0,Math.min(100,n))+"%";$("status").textContent=text;}
function readSettings(){return{topic:$("topic").value.trim()||"Your Topic",duration:Number($("duration").value),language:$("language").value,languageName:languages[$("language").value]?.name||$("language").value,audience:$("audience").value,contentStyle:$("contentStyle").value,hookStyle:$("hookStyle").value,voiceStyle:$("voiceStyle").value,visualStyle:$("visualStyle").value,transition:$("transition").value,captions:$("captions").checked,captionAnimation:$("captionAnimation").value,music:$("music").checked,volume:Number($("volume").value)}}
function abortGeneration(){if(generationController){try{generationController.abort()}catch(e){}generationController=null}generationSeq++;}
async function api(action,payload,signal){const res=await fetch("/api/engine",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload}),signal});const ct=res.headers.get("content-type")||"";if(!res.ok){let msg="Request failed";try{msg=(ct.includes("json")?(await res.json()).error:await res.text())||msg}catch(e){}throw new Error(msg)}return ct.includes("json")?res.json():res.blob();}
function clearVoice(){voiceBuffer=null;if(voiceBlobUrl){URL.revokeObjectURL(voiceBlobUrl);voiceBlobUrl=null}}
async function generateReel(){if(renderRunning)return;abortGeneration();const mySeq=generationSeq;generationController=new AbortController();const signal=generationController.signal;stopPreview();clearVoice();reel=null;setProgress(4,"Starting generation...");$("generateBtn").disabled=true;$("previewBtn").disabled=true;$("renderBtn").disabled=true;try{const s=readSettings();setProgress(12,`Building ${s.languageName} script...`);const data=await api("generate",s,signal);if(mySeq!==generationSeq)return;reel={...data,settings:s};renderUI();setProgress(60,"Generating cloud voiceover...");const tts=await api("tts",{language:s.language,languageName:s.languageName,voiceStyle:s.voiceStyle,text:[data.hook,...data.scenes.map(x=>x.text)].join("\n")},signal);if(mySeq!==generationSeq)return;voiceBlobUrl=URL.createObjectURL(tts);setProgress(82,"Preparing audio...");voiceBuffer=await decodeBlob(tts);if(mySeq!==generationSeq)return;setProgress(100,"Reel ready. Preview and Render now use the same audio.");$("voiceMeta").innerHTML=`<span class="pill ok">Cloud TTS ready</span><span class="pill">${languages[s.language]?.name||s.language}</span><span class="pill">${voiceBuffer.duration.toFixed(1)}s audio</span>`;$("previewBtn").disabled=false;$("renderBtn").disabled=false}catch(err){if(err.name==="AbortError")return;console.error(err);setProgress(0,err.message||"Generation failed. Check your API configuration.")}finally{if(mySeq===generationSeq){$("generateBtn").disabled=false;generationController=null}}}
async function decodeBlob(blob){const ab=await blob.arrayBuffer();const ac=new(window.AudioContext||window.webkitAudioContext)();const buf=await ac.decodeAudioData(ab.slice(0));await ac.close().catch(()=>{});return buf}
function renderUI(){$("hookOutput").textContent=reel.hook;$('voiceOutput').textContent=[reel.hook,...reel.scenes.map(s=>s.text)].join("\n\n");$('captionOutput').textContent=`${reel.caption}\n\n${(reel.hashtags||[]).join(" ")}`;const s=reel.settings;$('settingsOutput').textContent=`${s.duration}s • ${s.languageName} • ${s.audience} • ${s.contentStyle} • ${s.hookStyle} hook • ${s.voiceStyle} voice • ${s.visualStyle} • ${s.transition} • captions ${s.captions?"ON":"OFF"} • music ${s.music?"ON":"OFF"}`;renderTimeline();drawFrame(0)}
function getSegments(){if(!reel)return[];const items=[{title:"Hook",text:reel.hook,isHook:true},...reel.scenes.map(s=>({...s,isHook:false}))];const totalText=items.reduce((a,x)=>a+Math.max(1,x.text.length),0);let cursor=0;return items.map((x,i)=>{const dur=reel.settings.duration*(Math.max(1,x.text.length)/totalText);const seg={...x,start:cursor,end:cursor+dur,index:i};cursor+=dur;return seg})}
function renderTimeline(){const segs=getSegments();$('timeline').innerHTML=segs.filter(s=>!s.isHook).map((s,i)=>`<div class="scene"><div class="sceneNum">SCENE ${i+1}</div><div><div class="sceneTitle">${escapeHtml(s.title||`Scene ${i+1}`)}</div><div class="sceneText">${escapeHtml(s.text)}</div></div><div class="sceneTime">${s.start.toFixed(1)}–${s.end.toFixed(1)}s</div></div>`).join("")}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function colors(style,topic){const t=topic.toLowerCase();if(t.includes("ferrari")||t.includes("bmw")||t.includes("car")){if(style==="Neon")return["#190b1b","#081a2d"];if(style==="Minimal")return["#171717","#333333"];return["#160d0a","#182331"]}if(t.includes("chandrayaan")||t.includes("moon")||t.includes("space")){if(style==="Neon")return["#170f2c","#071c2b"];return["#090d1d","#10264d"]}if(style==="Neon")return["#230f2b","#06182d"];if(style==="Minimal")return["#151719","#2c3034"];return["#0b1020","#1b315f"]}
function roundRect(c,x,y,w,h,r){c.beginPath();c.roundRect(x,y,w,h,r);c.fill()}
function wrapText(text,maxWidth,font){ctx.font=font;const words=/\s/.test(text)?text.split(/\s+/):[...text];const lines=[];let line="";for(const word of words){const test=line?line+(/\s/.test(text)?" ":"")+word:word;if(ctx.measureText(test).width<=maxWidth)line=test;else{if(line)lines.push(line);line=word}}if(line)lines.push(line);return lines.length?lines:[""]}
function drawCentered(text,x,y,maxWidth,font,lineHeight,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.fillStyle="#fff";ctx.textAlign="center";const lines=wrapText(text,maxWidth,font);const total=lines.length*lineHeight;lines.forEach((l,i)=>ctx.fillText(l,x,y-total/2+i*lineHeight+lineHeight*.25));ctx.restore()}
function drawCaption(text,anim,local){ctx.save();let scale=1;let cy=canvas.height*.82;if(anim==="Pop")scale=.88+Math.min(.12,local*.6);if(anim==="Slide")cy=canvas.height*.9-local*canvas.height*.08;if(anim==="Fade")ctx.globalAlpha=Math.min(1,local*5);if(anim==="Type")text=text.slice(0,Math.max(1,Math.floor(text.length*Math.min(1,local*1.8))));ctx.translate(canvas.width/2,cy);ctx.scale(scale,scale);const lines=wrapText(text,420,"bold 22px Arial");const h=lines.length*34+34;ctx.fillStyle="rgba(0,0,0,.7)";roundRect(ctx,-230,-h/2,460,h,18);ctx.fillStyle="#fff";ctx.font="bold 22px Arial";ctx.textAlign="center";lines.forEach((l,i)=>ctx.fillText(l,0,-(lines.length-1)*17+i*34+8));ctx.restore()}
function drawFrame(seconds){if(!reel)return;const W=canvas.width,H=canvas.height;const segs=getSegments();let seg=segs[segs.length-1];for(const s of segs){if(seconds>=s.start&&seconds<=s.end){seg=s;break}}const local=Math.max(0,Math.min(1,(seconds-seg.start)/Math.max(.001,seg.end-seg.start)));const c=colors(reel.settings.visualStyle,reel.settings.topic);const g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,c[0]);g.addColorStop(1,c[1]);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
const glowX=W*(.2+.6*((Math.sin(seconds*.7)+1)/2));const glowY=H*(.22+.18*Math.sin(seconds*.55));const glow=ctx.createRadialGradient(glowX,glowY,10,glowX,glowY,380);glow.addColorStop(0,"rgba(120,150,255,.28)");glow.addColorStop(1,"rgba(0,0,0,0)");ctx.fillStyle=glow;ctx.fillRect(0,0,W,H);
ctx.globalAlpha=.24;ctx.strokeStyle="#fff";ctx.lineWidth=2;for(let i=0;i<6;i++){const px=(seconds*70+i*130)%W;ctx.beginPath();ctx.moveTo(px,0);ctx.lineTo(px-90,H);ctx.stroke()}ctx.globalAlpha=1;
ctx.textAlign="left";ctx.fillStyle="rgba(255,255,255,.55)";ctx.font="bold 19px Arial";ctx.fillText(seg.isHook?"HOOK":`SCENE ${seg.index}`,34,55);
let title=seg.title||"";if(seg.isHook)title=reel.settings.topic;drawCentered(title,W/2,H*.31,460,"bold 46px Arial",56);
drawCentered(seg.text,W/2,H*.48,430,"24px Arial",34,.96);
if(reel.settings.captions)drawCaption(seg.text,reel.settings.captionAnimation,local);
ctx.textAlign="left";ctx.fillStyle="rgba(255,255,255,.42)";ctx.font="bold 15px Arial";ctx.fillText("AI REEL MAKER",34,H-34);
ctx.textAlign="right";ctx.fillStyle="rgba(255,255,255,.3)";ctx.font="12px Arial";ctx.fillText(`${Math.min(reel.settings.duration,Math.max(0,seconds)).toFixed(1)}s / ${reel.settings.duration}s`,W-34,H-34)}
function connectVoiceAndMusic(ctxAudio,destination,withOutput){const voice=ctxAudio.createBufferSource();voice.buffer=voiceBuffer;const voiceGain=ctxAudio.createGain();voiceGain.gain.value=.92;voice.connect(voiceGain);voiceGain.connect(destination);if(withOutput)voiceGain.connect(ctxAudio.destination);activeNodes.push(voice,voiceGain);if(reel.settings.music)createMusic(ctxAudio,destination,withOutput);return voice}
function createMusic(ac,destination,withOutput){const gain=ac.createGain();gain.gain.value=(reel.settings.volume/100)*.11;gain.connect(destination);if(withOutput)gain.connect(ac.destination);const notes=[110,138.59,164.81,196,164.81,138.59,123.47,164.81];const beats=Math.ceil(reel.settings.duration/.5)+1;for(let i=0;i<beats;i++){const osc=ac.createOscillator(),env=ac.createGain();osc.type=reel.settings.contentStyle==="Cinematic"?"sine":"triangle";osc.frequency.value=notes[i%notes.length]*(i%8===0?2:1);const t=i*.5;env.gain.setValueAtTime(0,ac.currentTime+t);env.gain.linearRampToValueAtTime(.34,ac.currentTime+t+.035);env.gain.exponentialRampToValueAtTime(.001,ac.currentTime+t+.46);osc.connect(env);env.connect(gain);osc.start(ac.currentTime+t);osc.stop(ac.currentTime+t+.47);activeNodes.push(osc,env)}activeNodes.push(gain)}
async function preview(){if(!reel)return setProgress(0,"Generate the reel first.");if(renderRunning)return;stopPreview();if(!voiceBuffer)return setProgress(0,"Voiceover is not ready yet.");activeAudioContext=new(window.AudioContext||window.webkitAudioContext)();await activeAudioContext.resume();const voice=connectVoiceAndMusic(activeAudioContext,activeAudioContext.destination,true);const start=activeAudioContext.currentTime;voice.start();setProgress(0,"Playing preview...");const tick=()=>{if(!activeAudioContext)return;const elapsed=activeAudioContext.currentTime-start;drawFrame(Math.min(elapsed,reel.settings.duration));if(elapsed<reel.settings.duration){previewRAF=requestAnimationFrame(tick)}else{stopPreview();setProgress(100,"Preview finished.")}};previewRAF=requestAnimationFrame(tick);}
function stopPreview(){if(previewRAF){cancelAnimationFrame(previewRAF);previewRAF=null}for(const node of activeNodes){try{node.stop?.()}catch(e){}}activeNodes=[];if(activeAudioContext){activeAudioContext.close().catch(()=>{});activeAudioContext=null}if(reel)drawFrame(0)}
function supportedMime(){const types=["video/webm;codecs=vp9,opus","video/webm;codecs=vp8,opus","video/webm"];return types.find(t=>MediaRecorder.isTypeSupported(t))||""}
async function renderReel(){if(!reel||!voiceBuffer)return setProgress(0,"Generate the reel first.");if(renderRunning)return;stopPreview();renderRunning=true;$("renderBtn").disabled=true;$("previewBtn").disabled=true;$("generateBtn").disabled=true;setProgress(2,"Preparing render audio...");const ac=new(window.AudioContext||window.webkitAudioContext)();await ac.resume();activeAudioContext=ac;activeNodes=[];const videoStream=canvas.captureStream(30);const dest=ac.createMediaStreamDestination();const voice=connectVoiceAndMusic(ac,dest,false);const combined=new MediaStream();videoStream.getVideoTracks().forEach(t=>combined.addTrack(t));dest.stream.getAudioTracks().forEach(t=>combined.addTrack(t));const mime=supportedMime();let recorder;try{recorder=new MediaRecorder(combined,mime?{mimeType:mime,videoBitsPerSecond:5000000,audioBitsPerSecond:128000}:undefined)}catch(e){recorder=new MediaRecorder(combined)}const chunks=[];const done=new Promise(resolve=>{recorder.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data)};recorder.onerror=e=>resolve(e.error||new Error("Recorder error"));recorder.onstop=()=>resolve(null)});recorder.start(1000);const start=ac.currentTime;voice.start();function frame(){const elapsed=ac.currentTime-start;drawFrame(Math.min(elapsed,reel.settings.duration));const p=Math.min(99,elapsed/reel.settings.duration*100);setProgress(p,`Rendering ${Math.floor(p)}%...`);if(elapsed<reel.settings.duration){requestAnimationFrame(frame)}else{setTimeout(()=>recorder.stop(),250)}}requestAnimationFrame(frame);const err=await done;activeAudioContext=null;activeNodes=[];videoStream.getTracks().forEach(t=>t.stop());combined.getTracks().forEach(t=>t.stop());await ac.close().catch(()=>{});renderRunning=false;$("renderBtn").disabled=false;$("previewBtn").disabled=false;$("generateBtn").disabled=false;if(err){console.error(err);setProgress(0,"Render failed: "+(err.message||"MediaRecorder error"));return}const blob=new Blob(chunks,{type:recorder.mimeType||"video/webm"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`AI-Reel-${Date.now()}.webm`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);setProgress(100,"Render complete. Downloaded video contains the generated voiceover and background audio.")}
function newReel(){abortGeneration();stopPreview();clearVoice();reel=null;$("hookOutput").textContent="Generate a reel first.";$("voiceOutput").textContent="Voiceover will appear here.";$("voiceMeta").textContent="";$("captionOutput").textContent="Caption will appear here.";$("settingsOutput").textContent="No reel generated yet.";$("timeline").innerHTML='<div class="muted">Generate a reel to create scenes.</div>';setProgress(0,"Ready for a new reel.");drawBlank()}
function drawBlank(){ctx.fillStyle="#080b12";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle="rgba(255,255,255,.75)";ctx.textAlign="center";ctx.font="bold 30px Arial";ctx.fillText("AI Reel Maker",canvas.width/2,canvas.height/2-10);ctx.font="16px Arial";ctx.fillStyle="rgba(255,255,255,.45)";ctx.fillText("Generate a reel to begin",canvas.width/2,canvas.height/2+22)}
$("volume").addEventListener("input",()=>$('volumeText').textContent=$("volume").value+"%");$("language").addEventListener("change",()=>{$("languageInfo").textContent=`${languages[$("language").value]?.name||$("language").value} is selected. Nothing regenerates until you press Generate Reel.`});$("generateBtn").addEventListener("click",generateReel);$("previewBtn").addEventListener("click",preview);$("stopBtn").addEventListener("click",()=>{stopPreview();if(reel)setProgress(100,"Stopped.")});$("renderBtn").addEventListener("click",renderReel);$("newBtn").addEventListener("click",newReel);drawBlank();
